modLoader="javafml"
loaderVersion="[${lang_version},)"
issueTrackerURL="https://github.com/TheCBProject/CodeChickenLib"
license="GNU Lesser General Public License v2.1"

[[mods]]
	modId="codechickenlib"
	displayName="CodeChicken Lib"
	version="${file.jarVersion}"

	updateJSONURL="https://version-check.covers1624.net/check/?mod=CodeChickenLib&mc=${mc_version}"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8"
	authors="ChickenBones, covers1624"
	description='''
CodeChickenLib is a library of systems to help make various aspects of minecraft modding easier.
It contains libraries for 3D math and transformations, model rendering, packets, config, colours, asm and a few other things..
    '''
[[dependencies.codechickenlib]]
	modId="forge"
	mandatory=true
	versionRange="[${forge_version},)"
	ordering="NONE"
	side="BOTH"
[[dependencies.codechickenlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"

