modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/TheCBProject/CodeChickenLib"
license="GNU Lesser General Public License v2.1"

[[mods]]
	modId="codechickenlib"
	displayName="CodeChicken Lib"
	version="${version}"

	updateJSONURL="https://version-check.covers1624.net/check/?mod=CodeChickenLib&mc=${mc_version}"
	displayURL="http://chickenbones.net/Pages/links.html"
	authors="ChickenBones, covers1624"
	description='''
CodeChickenLib is a library of systems to help make various aspects of minecraft modding easier.
It contains libraries for 3D math and transformations, model rendering, packets, config, colours, asm and a few other things..
    '''
[[dependencies.codechickenlib]]
	modId="forge"
	mandatory=true
	versionRange="[35.1,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.codechickenlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"

